### PR TITLE
Add transforms3d and rise to environment

### PR DESCRIPTION
**Pull request by effigies**

### CODE REVIEW

**Comment by arokem** [comment]
Does RISE work in jupyterlab? I believe not (https://rise.readthedocs.io/en/stable/usage.html#jupyterlab). Or do you intend to switch to the classic notebook to use it?

**Comment by effigies** [comment]
Oh, that didn't occur to me. I'm working in notebook. Is there an easy way to open classic notebooks from the jupyterlab interface?

**Comment by arokem** [comment]
Yes: https://hub.neurohackademy.org/user/_username_/tree

**Comment by arokem** [comment]
Sorry: had to update that last comment, because angle brackets.

**Comment by arokem** [comment]
For now, let me just merge this.

**Pull request merged**
